// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ControlView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex gap-2 mb-2\"><button hx-post=\"/pause\" class=\"px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded\" hx-swap=\"none\">⏸/▶</button> <button hx-post=\"/speed-down\" class=\"px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded\" hx-swap=\"none\">⏪</button> <button hx-post=\"/speed-up\" class=\"px-2 py-1 bg-gray-700 hover:bg-gray-600 rounded\" hx-swap=\"none\">⏩</button> <button hx-post=\"/spawn-agent\" class=\"px-2 py-1 bg-green-700 hover:bg-green-600 rounded\" hx-swap=\"none\">🟢 Agent</button> <button hx-post=\"/spawn-food\" class=\"px-2 py-1 bg-green-500 hover:bg-green-400 rounded\" hx-swap=\"none\">🍏 Food</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
