// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MainView(content templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta charset=\"utf-8\"><title>TinyWorlds</title><script src=\"https://unpkg.com/htmx.org@2.0.8/dist/htmx.min.js\"></script><link href=\"/static/tailwind.css\" rel=\"stylesheet\"><script type=\"module\" src=\"/js/ws.js\"></script><script type=\"module\" src=\"/js/canvas.js\"></script></head><style>\r\n      .cell {width: 16px; height: 16px;}\r\n      .agent { \r\n        transition: transform 0.2s linear, opacity 0.2s ease-out;\r\n        will-change: transform;\r\n      }\r\n      .agent.dead {\r\n        opacity: 0;\r\n      }\r\n      .agent.new {\r\n        transform: scale(0.5);\r\n        opacity: 0;\r\n      }\r\n    </style><body class=\"bg-gray-900 text-gray-100 flex flex-col items-center min-h-screen py-6\"><h1 class=\"text-3xl font-bold mb-4\">🌍 TinyWorlds</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ControlView().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<canvas width=\"320\" height=\"320\" class=\"border-2 border-white\" id=\"worldCanvas\"></canvas><!-- <div id=\"world\" class=\"grid border-2 border-white mb-4\"></div> --><!-- <div id=\"stats\" class=\"text-gray-400\"></div> --><p class=\"mt-4 text-sm text-gray-400\">Agent moves every second & eats green food 🍎</p></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
